# This is a basic workflow to help you get started with Actions

name: Pc/Desktop

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Desktop:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp.git
          haxelib git lime https://github.com/MobilePorting/lime
          haxelib install openfl 9.2.2
          haxelib install flixel 5.2.2
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 2.10.0
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib install hxcpp-debug-server
          haxelib install actuate
          haxelib install hxCodec 2.5.1
          haxelib install hscript
          haxelib install SScript
          haxelib install away3d
          haxelib git lime https://github.com/MobilePorting/lime
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc.git
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved.git
      - name: Compile (Windows)
        if: startsWith(matrix.os, 'windows')
        run: haxelib run lime build windows -D officialBuild
      - name: Upload artifacts & release assets
        uses: actions/action-upload-artifacts-and-release-assets@main
        with:
           path: export\release\windows\bin\*
           if-no-files-found: warn
